### ISSUE TITLE
The app should handle multiple events

### ISSUE THREAD

**Issue by Cloud11PL** [saleor/saleor-app-mailing#15]
Currently the app only handles "ORDER_CREATED" event. The app should be able to handle multiple events. App could register for all events and then internally disable them - user should decide which event should send an email or not. Or we could start with few events and then let user add more by generating new webhooks for those events. 

MJML, GraphQL subscription and their corresponding event should be stored in app's metadata. User should be able to pick which event is currently edited from a dropdown or a list. 

Next step would be to create some sample email templates and schemas for all events.

**Comment by korycins** [comment]
One thing that needs to be done on Saleor core side first is implementing missing webhooks like password-reset-event. Saleor Core has webhook NOTIFY, which contains all notification events but it doesn't have subscription support.

**Comment by krzysztofwolski** [comment]
Blocked by https://github.com/saleor/saleor/issues/11959

**Comment by krzysztofwolski** [comment]
List of the events from the user emails plugin:

- [ ]  `account_confirmation`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ] `account_password_reset`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ]  `account_change_email_request`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ]  `account_change_email_confirm`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ]  `account_delete`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ]  `account_set_customer_password`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [x]  `invoice_ready`
    - :white_check_mark: Done
- [x]  `order_confirmation`
    - :white_check_mark: DONE as ORDER CREATED
- [x]  `order_confirmed`
    - :white_check_mark: DONE
- [x]  `order_fulfillment_confirmation`
    - :white_check_mark: DONE  as order fulfilled
- [ ]  `order_fulfillment_update`
    - :hourglass_flowing_sand:/:no_entry: TODO: should it be an FULFILLMENT_APPROVED? CANCELLED?
- [x]  `order_payment_confirmation`
    - :white_check_mark: DONE  as order fully paid
- [x]  `order_canceled`
    - :white_check_mark: DONE
- [ ]  `order_refund_confirmation`
    - :no_entry: ATM Core does not have support for such event in async webhooks
- [ ]  `send_gift_card`
    - :no_entry: ATM Core does not have support for such event in async webhooks

**Comment by lkostrowski** [comment]
Closing, issue is tracked here https://github.com/saleor/apps/issues/78
