### ISSUE TITLE
New email providers

### ISSUE THREAD

**Issue by korycins** [saleor/saleor-app-mailing#16]
For mvp we used smtp and mailhog clients. In future releases, it would be good to add more providers that user can choose to use, like sendgrid.

**Comment by magul** [comment]
Just FYI we have [`saleor-app-klavyio`](https://github.com/saleor/saleor-app-klaviyo), which solely responsibility is sending emails. I recall we had a conversation about having multi-provide app for that (including sendgrid and mandrill, as I recall), but for some reason we decided to split these apps per-provider.

(you can even see, that in fact it was prepared for multiple providers, as we even prepared abstract provider types see e.g.: https://github.com/saleor/saleor-app-klaviyo/blob/canary/lib/klaviyo.ts#L1)

**Comment by lkostrowski** [comment]
@magul thats correct, at the moment we will ship Klaviyo separately, but long term we will try to unify notification providers (actually this app is notifications, not mailing only, because sending SMS or Slack is the same thing). We will merge Klaviyo and Slack into Hub and add more providers
